// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import sqs "github.com/EurosportDigital/global-transcoding-platform/lib/aws/sqs"

// Listener is an autogenerated mock type for the Listener type
type Listener struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *Listener) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Poll provides a mock function with given fields: _a0, _a1
func (_m *Listener) Poll(_a0 chan<- sqs.Message, _a1 bool) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(chan<- sqs.Message, bool) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
