// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// S3Client is an autogenerated mock type for the S3Client type
type S3Client struct {
	mock.Mock
}

// CheckResourceExistance provides a mock function with given fields: bucket, key
func (_m *S3Client) CheckResourceExistance(bucket string, key string) (bool, error) {
	ret := _m.Called(bucket, key)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(bucket, key)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(bucket, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
