// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	monitoring "github.com/EurosportDigital/global-transcoding-platform/lib/monitoring"
	mock "github.com/stretchr/testify/mock"
)

// EventReporter is an autogenerated mock type for the EventReporter type
type EventReporter struct {
	mock.Mock
}

// Emit provides a mock function with given fields: e
func (_m *EventReporter) Emit(e *monitoring.Event) {
	_m.Called(e)
}

// EmitSimple provides a mock function with given fields: title, description
func (_m *EventReporter) EmitSimple(title string, description string) {
	_m.Called(title, description)
}
