// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	monitoring "github.com/EurosportDigital/global-transcoding-platform/lib/monitoring"
	mock "github.com/stretchr/testify/mock"
)

// HealthCheckReporter is an autogenerated mock type for the HealthCheckReporter type
type HealthCheckReporter struct {
	mock.Mock
}

// Report provides a mock function with given fields: hc
func (_m *HealthCheckReporter) Report(hc *monitoring.HealthCheck) {
	_m.Called(hc)
}

// ReportSimple provides a mock function with given fields: name, status
func (_m *HealthCheckReporter) ReportSimple(name string, status monitoring.HealthCheckStatus) {
	_m.Called(name, status)
}
